{{- if and .Values.config.health.enabled .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kermi2mqtt.fullname" . }}
  labels:
    {{- include "kermi2mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: health
      port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "kermi2mqtt.selectorLabels" . | nindent 4 }}
{{- end }}
